export const cartActionTypes = {
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
    INCRIMENT_ITEM_QUANTITY: "CHANGE_ITEM_QUANTITY",
    DECRIMENT_ITEM_QUANTITY: "DECRIMENT_ITEM_QUANTITY",
};
